Octobot:
  queues:
    - { name: tacotruck,
        protocol: beanstalk,
        host: localhost,
        port: 11300,
        workers: 1,
        priority: 10
      }

  metrics_port: 1228

  email_enabled: false
  email_from: ohai@example.com
  email_to: ohno@itsbroke.com
  email_hostname: localhost
  email_server: smtp.gmail.com
  email_port: 465
  email_ssl: true
  email_auth: true
  email_username: username
  email_password: password

  # startup_hook: org.example.taquito.StartupHook
  # shutdown_hook: org.example.taquito.ShutdownHook